import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";
import { decodeToken } from "@/lib/auth";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ scanId: string }> }
) {
  const authHeader = request.headers.get("authorization");
  const token = authHeader?.startsWith("Bearer ") ? authHeader.slice(7) : null;
  if (!token) {
    return Response.json({ detail: "Missing token" }, { status: 401 });
  }

  const payload = decodeToken(token);
  if (!payload) {
    return Response.json({ detail: "Invalid token" }, { status: 401 });
  }

  const { scanId } = await params;
  const format = request.nextUrl.searchParams.get("format");

  const scan = await prisma.scan.findFirst({
    where: { id: scanId, userId: payload.sub },
    include: { vulnerabilities: true },
  });

  if (!scan) {
    return Response.json({ detail: "Scan not found" }, { status: 404 });
  }

  const report = scan.finalReport as Record<string, unknown>;
  const steps = (Array.isArray(report.remediation_steps) ? report.remediation_steps : []) as string[];

  if (format === "html") {
    const html = buildHtmlReport(scan, report, steps);
    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="aether-report-${scanId}.html"`,
      },
    });
  }

  return Response.json({
    scan_id: scan.id,
    target_url: scan.targetUrl,
    status: scan.status,
    threat_level: scan.threatLevel,
    created_at: scan.createdAt,
    completed_at: scan.completedAt,
    summary: report.risk_impact || null,
    remediation_steps: steps,
    vulnerabilities: scan.vulnerabilities.map((v) => ({
      id: v.id,
      title: v.title,
      severity: v.severity,
      category: v.category,
      detail: v.detail,
      attack_vector: v.attackVector,
      detected_threat: v.detectedThreat,
      evidence: v.evidence,
    })),
  });
}

function buildHtmlReport(
  scan: { targetUrl: string; threatLevel: string; createdAt: Date; completedAt: Date | null; vulnerabilities: Array<{ severity: string; title: string; category: string; detail: string }> },
  report: Record<string, unknown>,
  steps: string[]
) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AETHER Report - ${scan.targetUrl}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
    h1 { font-size: 24px; border-bottom: 2px solid #FFC107; padding-bottom: 8px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
    .severity { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
    .critical { background: #fef2f2; color: #dc2626; }
    .high { background: #fff7ed; color: #ea580c; }
    .medium { background: #fefce8; color: #ca8a04; }
    .low { background: #f0fdf4; color: #16a34a; }
    .finding { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
    .finding h3 { font-size: 16px; margin: 0 0 4px; }
    .finding p { font-size: 14px; color: #666; margin: 8px 0 0; }
  </style>
</head>
<body>
  <h1>AETHER Security Report</h1>
  <div class="meta">
    <div>Target: ${scan.targetUrl}</div>
    <div>Threat Level: <span class="severity ${scan.threatLevel}">${(scan.threatLevel || "unknown").toUpperCase()}</span></div>
    <div>Date: ${scan.createdAt.toISOString().split("T")[0]}</div>
    <div>Duration: ${scan.completedAt ? Math.round((scan.completedAt.getTime() - scan.createdAt.getTime()) / 1000) + "s" : "In Progress"}</div>
  </div>
  <h2>Summary</h2>
  <p>${report.risk_impact || "No summary available."}</p>
  ${scan.vulnerabilities.length > 0 ? `<h2>Findings (${scan.vulnerabilities.length})</h2>${scan.vulnerabilities.map((v) => `<div class="finding"><span class="severity ${v.severity}">${v.severity}</span><h3>${v.title}</h3><p><strong>Category:</strong> ${v.category}</p><p>${v.detail}</p></div>`).join("")}` : "<p>No vulnerabilities found.</p>"}
  ${steps.length > 0 ? `<h2>Remediation Steps</h2><ol>${steps.map((s) => `<li>${s}</li>`).join("")}</ol>` : ""}
  <div style="margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #999;">Generated by AETHER</div>
</body>
</html>`;
}
